if: tag IS present

language: generic

env:
    global:
        - IS_RELEASE=$(git ls-remote origin | grep "$TRAVIS_COMMIT\s\+refs/heads/master")

services:
  - docker

deploy:
  - provider: script
    script: server/travis.sh
    on:
      tags: true

  - provider: releases
    script: ./travis.sh
    file_glob: true
    file: dist/*
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
      branch: master