if: tag IS present

language: generic

services:
  - docker

stages:
  - DockerHub Release
  - GitHub Release

jobs:
  include:
    - stage: DockerHub Release
      deploy:
        provider: script
        script: server/travis.sh
        on:
          tags: true

    - stage: GitHub Release
      script: ./travis.sh
      deploy:
        provider: releases
        file_glob: true
        file: dist/*
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
