version: '2.0'
services:
    c:
        restart: always
        build: '.'
        image: boxmein-forks/c-server
        ports:
            - 8099:80
        environment:
            HOST: '0.0.0.0'
            PORT: '80'
            STORAGE_BACKEND: file
            STORAGE_PATH: /data
        volumes:
            - data:/data

volumes:
    data:
