on: 
  push:
    branches:
      - master 

env:
  DOCKER_IMAGE: ghcr.io/boxmein-forks/c-server
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - run: |
          docker buildx build \
            --platform=linux/amd64,linux/aarch64 \
            --tag ${{ env.DOCKER_IMAGE }} \
            --push \
            .
